#ifndef DLP_DEVICES_MOTORS_CORRECTION_CAMENDMOTOR_H_
#define DLP_DEVICES_MOTORS_CORRECTION_CAMENDMOTOR_H_


class CAmendMotor
{
public:
    CAmendMotor();
    ~CAmendMotor();

private:

};

#endif //DLP_DEVICES_MOTORS_CORRECTION_CAMENDMOTOR_H_
