#ifndef DLP_DEVICES_MOTORS_CORRECTION_CDRIVERMOTOR_H_
#define DLP_DEVICES_MOTORS_CORRECTION_CDRIVERMOTOR_H_

class CDriverMotor
{
public:
    CDriverMotor();
    ~CDriverMotor();


private:


};

#endif //DLP_DEVICES_MOTORS_CORRECTION_CDRIVERMOTOR_H_
