###########################################
# devices Makefile
#                            By Guo Jianwei
#                                2015-09-29
#                  EMAIL: gjianw217@163.com
###########################################
all:motors rheostat encoder switch
motors:
	$(MAKE) -C motors
rheostat:
	$(MAKE) -C rheostat
encoder:
	$(MAKE) -C encoder
switch:
	$(MAKE) -C switch
.PHONY:all motors rheostat encoder switch
