###########################################
# demo Makefile
#                            By Guo Jianwei
#                                2015-10-12
#                  EMAIL: gjianw217@163.com
###########################################
all:drivers network robot devices client
drivers:
	$(MAKE) -C drivers
network:
	$(MAKE) -C network
robot:
	$(MAKE) -C robot
devices:
	$(MAKE) -C devices
client:
	$(MAKE) -C client
.PHONY:all drivers network robot devices client
